{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quote-chart.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quote-chart.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "quote-chart.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
