FROM spotify/techdocs:1.2.6

RUN apt-get update  \
    && apt-get install -y \
      chromium \
    && rm -rf /var/lib/apt/lists/*

RUN pip install \
    markdown-inline-mermaid==1.0.4 \
    mkdocs-mermaid2-plugin==1.2.1 \
    mkdocs-macros-plugin==1.3.7

# List of plugins we could install:
# https://github.com/backstage/mkdocs-techdocs-core