version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/backstage'
      - '/backstage/packages/app'
      - '/backstage/packages/backend'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: "@backstage/*"
      - dependency-name: "@spotify/*"
      - dependency-name: "@testing-library/*"
      - dependency-name: "typescript"
      - dependency-name: "prettier"
      - dependency-name: "better-sqlite3"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
