apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-application
  namespace: webgrip
  title: Backstage Application
  description: |
    The Backstage Application is the main application that serves the Backstage UI. It is a React application that is built with TypeScript.
  labels:
    tier: "2"
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
    - title: Development URL
      url: https://backstage.test
      icon: dashboard
  tags:
    - backstage
  annotations:
    backstage.io/adr-location: docs/adr
    github.com/project-slug: webgrip/backstage
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: my-kubernetes-component
    backstage.io/code-coverage: enabled
    simpleicons.org/icon-slug: backstage
spec:
  type: service
  owner: group:webgrip/backstage
  lifecycle: experimental
  system: backstage-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage-system
  namespace: webgrip
  title: Backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
spec:
  owner: group:webgrip/backstage
  domain: webgrip/operations-domain
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-application-postgres
  namespace: webgrip
  title: Backstage Repository
  description: |
    The Postgres database for the Backstage application. It has pgvector and uuid-ossp extensions enabled.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: webgrip/backstage
    simpleicons.org/icon-slug: postgres
  tags:
    - backstage
spec:
  type: database
  owner: group:webgrip/backstage
  system: backstage-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: biogroei-system
  namespace: webgrip
  title: Biogroei
  description: |
    The Biogroei system is responsible for all things related to the Biogroei webshop.
  labels:
    tier: "2"
  annotations:
    backstage.io/techdocs-ref: dir:.
    simpleicons.org/icon-slug: magento
  tags:
    - biogroei
  links:
    - url: https://www.biogroei.nl/
      title: Webshop
      icon: magento
      type: website
spec:
  owner: group:webgrip/infrastructure
  domain: webgrip/telemetry-domain
  type: product
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: biogroei-magento
  namespace: webgrip
  title: Magento
  description: |
    Magento is an open-source e-commerce platform written in PHP.
  labels:
    tier: "2"
  annotations:
    backstage.io/adr-location: docs/adrs
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=biogroei-magento'
    github.com/project-slug: webgrip/monitoring-platform
    sentry.io/project-slug: biogroei
    simpleicons.org/icon-slug: magento
    newrelic.com/dashboard-guid: 'MzI0NjMxMHxWSVp8REFTSEJPQVJEfGRhOjQ0ODQwNg'
  tags:
    - magento
    - biogroei
  links:
    - url: https://www.biogroei.nl/
      title: Webshop
      icon: magento
      type: website
spec:
  type: website
  lifecycle: production
  owner: group:webgrip/infrastructure
  system: biogroei-system
