site_name: 'Monitoring Platform Docs'

theme:
  name: 'material'

nav:
  - Home: index.md
  - Architecture: architecture.md

# https://www.mkdocs.org/user-guide/configuration
plugins:
  - techdocs-core:
      use_material_search: true
  - search:
      min-search-length: 2

markdown_extensions:
  - markdown_inline_mermaid
  - markdown_inline_graphviz
