site_name: 'Monitoring Platform Docs'

theme:
  name: 'material'

nav:
  - Home: index.md
  - Architecture: architecture.md

# https://www.mkdocs.org/user-guide/configuration
plugins:
  - techdocs-core
  - search:
      min-search-length: 2
  - mermaid2:
      arguments:
        securityLevel: 'loose'

markdown_extensions:
  - markdown_inline_mermaid
