site_name: 'Vendic Backstage Application TechDocs'
site_description: 'Contains a few examples for how to make and use Backstage TechDocs'

theme:
  name: 'material'

nav:
  - Home: index.md
  - Diagrams (Mermaid, GraphViz): diagrams.md

# https://www.mkdocs.org/user-guide/configuration
plugins:
  - techdocs-core:
      use_material_search: true
  - search:
      min-search-length: 2
      prebuild_index: true
      indexing: full
  - mermaid2:
      arguments:
        securityLevel: 'loose'
  - macros

markdown_extensions:
  - markdown_inline_mermaid
  - markdown_inline_graphviz
