on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        description: 'DockerHub username'
        required: true
      DOCKER_TOKEN:
        description: 'DockerHub token'
        required: true

name: Build

jobs:
  build-docker-image-backstage-application:
    name: 'Build Backstage Application'
    runs-on: self-hosted
    environment: ${{ inputs.github-environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Yarn install --immutable
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable
          dir: 'backstage'

      - name: Yarn tsc
        uses: borales/actions-yarn@v4
        with:
          cmd: tsc
          dir: 'backstage'

      - name: Yarn build:backend
        uses: borales/actions-yarn@v4
        with:
          cmd: build:backend
          dir: 'backstage'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: backstage
          file: packages/backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            webgrip/backstage-application:latest
            webgrip/backstage-application:${{ github.sha }}
