on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        description: 'DockerHub username'
        required: true
      DOCKER_TOKEN:
        description: 'DockerHub token'
        required: true
  workflow_dispatch:

name: Build

jobs:
  build-docker-image-backstage-application:
    name: 'Build Backstage Application'
    runs-on: self-hosted
    environment: ${{ inputs.github-environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: backstage
          file: backstage/Dockerfile-multistage
          target: runtime
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            webgrip/backstage-application:latest
            webgrip/backstage-application:${{ github.sha }}

  build-docker-image-backstage-application-postgres:
    name: 'Build Postgres'
    runs-on: self-hosted
    environment: ${{ inputs.github-environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: backstage
          file: backstage/Dockerfile-multistage
          target: runtime
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            webgrip/backstage-application-postgres:latest
            webgrip/backstage-application-postgres:${{ github.sha }}
