name: "[Workflow] On Push"

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-on-push

jobs:
  placeholder:
    runs-on: self-hosted
    steps:
      - name: Placeholder
        run: echo "Placeholder"
#  build:
#    uses: ./.github/workflows/build.yml
#    secrets:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
