concurrency:
  group: push-${{ github.branch }}
on:
  push:
    branches:
      - 'main'
name: Push Workflow
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Placeholder"
#  build:
#    uses: ./.github/workflows/build.yml
#    secrets:
#      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
