name: "[Workflow] On Documentation Change"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/techdocs/**'
      - '.github/workflows/update_techdocs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: |
          python -m pip install \
            mkdocs-techdocs-core==1.5.2\
            markdown-inline-mermaid==1.0.4 \
            mkdocs-mermaid2-plugin==1.2.1 \
            mkdocs-macros-plugin==1.3.7

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose --output-dir techdocs-site --source-dir docs/techdocs

      - name: Put in artifact
        uses: actions/upload-artifact@v4
        with:
          name: techdocs-site
          path: techdocs-site